import zipfile
import os
import numpy as np

# extraction zip
#zip_path = "/home/onyxia/work/datasets/stanford_cars.zip"
#with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#    zip_ref.extractall("/home/onyxia/work/datasets")

checkpoint_path = 'python DetailCLIP/eval_zeroshot.py --resume /home/onyxia/work/DetailCLIP/checkpoint_best.pt'

timm_path = '/usr/local/lib/python3.12/site-packages/timm/models'

dataset_path = "/home/onyxia/work/datasets/split_CUB200_2011/test"
#titles = [d for d in os.listdir(dataset_path) if os.path.isdir(os.path.join(dataset_path, d))]
#titles.sort()
titles = ['Black footed Albatross', 'Laysan Albatross', 'Sooty Albatross', 'Groove billed Ani', 'Crested Auklet', 'Least Auklet', 'Parakeet Auklet', 'Rhinoceros Auklet', 'Brewer Blackbird', 'Red winged Blackbird', 'Rusty Blackbird', 'Yellow headed Blackbird', 'Bobolink', 'Indigo Bunting', 'Lazuli Bunting', 'Painted Bunting', 'Cardinal', 'Spotted Catbird', 'Gray Catbird', 'Yellow breasted Chat', 'Eastern Towhee', 'Chuck will Widow', 'Brandt Cormorant', 'Red faced Cormorant', 'Pelagic Cormorant', 'Bronzed Cowbird', 'Shiny Cowbird', 'Brown Creeper', 'American Crow', 'Fish Crow', 'Black billed Cuckoo', 'Mangrove Cuckoo', 'Yellow billed Cuckoo', 'Gray crowned Rosy Finch', 'Purple Finch', 'Northern Flicker', 'Acadian Flycatcher', 'Great Crested Flycatcher', 'Least Flycatcher', 'Olive sided Flycatcher', 'Scissor tailed Flycatcher', 'Vermilion Flycatcher', 'Yellow bellied Flycatcher', 'Frigatebird', 'Northern Fulmar', 'Gadwall', 'American Goldfinch', 'European Goldfinch', 'Boat tailed Grackle', 'Eared Grebe', 'Horned Grebe', 'Pied billed Grebe', 'Western Grebe', 'Blue Grosbeak', 'Evening Grosbeak', 'Pine Grosbeak', 'Rose breasted Grosbeak', 'Pigeon Guillemot', 'California Gull', 'Glaucous winged Gull', 'Heermann Gull', 'Herring Gull', 'Ivory Gull', 'Ring billed Gull', 'Slaty backed Gull', 'Western Gull', 'Anna Hummingbird', 'Ruby throated Hummingbird', 'Rufous Hummingbird', 'Green Violetear', 'Long tailed Jaeger', 'Pomarine Jaeger', 'Blue Jay', 'Florida Jay', 'Green Jay', 'Dark eyed Junco', 'Tropical Kingbird', 'Gray Kingbird', 'Belted Kingfisher', 'Green Kingfisher', 'Pied Kingfisher', 'Ringed Kingfisher', 'White breasted Kingfisher', 'Red legged Kittiwake', 'Horned Lark', 'Pacific Loon', 'Mallard', 'Western Meadowlark', 'Hooded Merganser', 'Red breasted Merganser', 'Mockingbird', 'Nighthawk', 'Clark Nutcracker', 'White breasted Nuthatch', 'Baltimore Oriole', 'Hooded Oriole', 'Orchard Oriole', 'Scott Oriole', 'Ovenbird', 'Brown Pelican', 'White Pelican', 'Western Wood Pewee', 'Sayornis', 'American Pipit', 'Whip poor Will', 'Horned Puffin', 'Common Raven', 'White necked Raven', 'American Redstart', 'Geococcyx', 'Loggerhead Shrike', 'Great Grey Shrike', 'Baird Sparrow', 'Black throated Sparrow', 'Brewer Sparrow', 'Chipping Sparrow', 'Clay colored Sparrow', 'House Sparrow', 'Field Sparrow', 'Fox Sparrow', 'Grasshopper Sparrow', 'Harris Sparrow', 'Henslow Sparrow', 'Le Conte Sparrow', 'Lincoln Sparrow', 'Nelson Sharp tailed Sparrow', 'Savannah Sparrow', 'Seaside Sparrow', 'Song Sparrow', 'Tree Sparrow', 'Vesper Sparrow', 'White crowned Sparrow', 'White throated Sparrow', 'Cape Glossy Starling', 'Bank Swallow', 'Barn Swallow', 'Cliff Swallow', 'Tree Swallow', 'Scarlet Tanager', 'Summer Tanager', 'Artic Tern', 'Black Tern', 'Caspian Tern', 'Common Tern', 'Elegant Tern', 'Forsters Tern', 'Least Tern', 'Green tailed Towhee', 'Brown Thrasher', 'Sage Thrasher', 'Black capped Vireo', 'Blue headed Vireo', 'Philadelphia Vireo', 'Red eyed Vireo', 'Warbling Vireo', 'White eyed Vireo', 'Yellow throated Vireo', 'Bay breasted Warbler', 'Black and white Warbler', 'Black throated Blue Warbler', 'Blue winged Warbler', 'Canada Warbler', 'Cape May Warbler', 'Cerulean Warbler', 'Chestnut sided Warbler', 'Golden winged Warbler', 'Hooded Warbler', 'Kentucky Warbler', 'Magnolia Warbler', 'Mourning Warbler', 'Myrtle Warbler', 'Nashville Warbler', 'Orange crowned Warbler', 'Palm Warbler', 'Pine Warbler', 'Prairie Warbler', 'Prothonotary Warbler', 'Swainson Warbler', 'Tennessee Warbler', 'Wilson Warbler', 'Worm eating Warbler', 'Yellow Warbler', 'Northern Waterthrush', 'Louisiana Waterthrush', 'Bohemian Waxwing', 'Cedar Waxwing', 'American Three toed Woodpecker', 'Pileated Woodpecker', 'Red bellied Woodpecker', 'Red cockaded Woodpecker', 'Red headed Woodpecker', 'Downy Woodpecker', 'Bewick Wren', 'Cactus Wren', 'Carolina Wren', 'House Wren', 'Marsh Wren', 'Rock Wren', 'Winter Wren', 'Common Yellowthroat']
short_labels = ['Black footed Albatross', 'Laysan Albatross', 'Sooty Albatross', 'Groove billed Ani', 'Crested Auklet', 'Least Auklet', 'Parakeet Auklet', 'Rhinoceros Auklet', 'Brewer Blackbird', 'Red winged Blackbird', 'Rusty Blackbird', 'Yellow headed Blackbird', 'Bobolink', 'Indigo Bunting', 'Lazuli Bunting', 'Painted Bunting', 'Cardinal', 'Spotted Catbird', 'Gray Catbird', 'Yellow breasted Chat', 'Eastern Towhee', 'Chuck will Widow', 'Brandt Cormorant', 'Red faced Cormorant', 'Pelagic Cormorant', 'Bronzed Cowbird', 'Shiny Cowbird', 'Brown Creeper', 'American Crow', 'Fish Crow', 'Black billed Cuckoo', 'Mangrove Cuckoo', 'Yellow billed Cuckoo', 'Gray crowned Rosy Finch', 'Purple Finch', 'Northern Flicker', 'Acadian Flycatcher', 'Great Crested Flycatcher', 'Least Flycatcher', 'Olive sided Flycatcher', 'Scissor tailed Flycatcher', 'Vermilion Flycatcher', 'Yellow bellied Flycatcher', 'Frigatebird', 'Northern Fulmar', 'Gadwall', 'American Goldfinch', 'European Goldfinch', 'Boat tailed Grackle', 'Eared Grebe', 'Horned Grebe', 'Pied billed Grebe', 'Western Grebe', 'Blue Grosbeak', 'Evening Grosbeak', 'Pine Grosbeak', 'Rose breasted Grosbeak', 'Pigeon Guillemot', 'California Gull', 'Glaucous winged Gull', 'Heermann Gull', 'Herring Gull', 'Ivory Gull', 'Ring billed Gull', 'Slaty backed Gull', 'Western Gull', 'Anna Hummingbird', 'Ruby throated Hummingbird', 'Rufous Hummingbird', 'Green Violetear', 'Long tailed Jaeger', 'Pomarine Jaeger', 'Blue Jay', 'Florida Jay', 'Green Jay', 'Dark eyed Junco', 'Tropical Kingbird', 'Gray Kingbird', 'Belted Kingfisher', 'Green Kingfisher', 'Pied Kingfisher', 'Ringed Kingfisher', 'White breasted Kingfisher', 'Red legged Kittiwake', 'Horned Lark', 'Pacific Loon', 'Mallard', 'Western Meadowlark', 'Hooded Merganser', 'Red breasted Merganser', 'Mockingbird', 'Nighthawk', 'Clark Nutcracker', 'White breasted Nuthatch', 'Baltimore Oriole', 'Hooded Oriole', 'Orchard Oriole', 'Scott Oriole', 'Ovenbird', 'Brown Pelican', 'White Pelican', 'Western Wood Pewee', 'Sayornis', 'American Pipit', 'Whip poor Will', 'Horned Puffin', 'Common Raven', 'White necked Raven', 'American Redstart', 'Geococcyx', 'Loggerhead Shrike', 'Great Grey Shrike', 'Baird Sparrow', 'Black throated Sparrow', 'Brewer Sparrow', 'Chipping Sparrow', 'Clay colored Sparrow', 'House Sparrow', 'Field Sparrow', 'Fox Sparrow', 'Grasshopper Sparrow', 'Harris Sparrow', 'Henslow Sparrow', 'Le Conte Sparrow', 'Lincoln Sparrow', 'Nelson Sharp tailed Sparrow', 'Savannah Sparrow', 'Seaside Sparrow', 'Song Sparrow', 'Tree Sparrow', 'Vesper Sparrow', 'White crowned Sparrow', 'White throated Sparrow', 'Cape Glossy Starling', 'Bank Swallow', 'Barn Swallow', 'Cliff Swallow', 'Tree Swallow', 'Scarlet Tanager', 'Summer Tanager', 'Artic Tern', 'Black Tern', 'Caspian Tern', 'Common Tern', 'Elegant Tern', 'Forsters Tern', 'Least Tern', 'Green tailed Towhee', 'Brown Thrasher', 'Sage Thrasher', 'Black capped Vireo', 'Blue headed Vireo', 'Philadelphia Vireo', 'Red eyed Vireo', 'Warbling Vireo', 'White eyed Vireo', 'Yellow throated Vireo', 'Bay breasted Warbler', 'Black and white Warbler', 'Black throated Blue Warbler', 'Blue winged Warbler', 'Canada Warbler', 'Cape May Warbler', 'Cerulean Warbler', 'Chestnut sided Warbler', 'Golden winged Warbler', 'Hooded Warbler', 'Kentucky Warbler', 'Magnolia Warbler', 'Mourning Warbler', 'Myrtle Warbler', 'Nashville Warbler', 'Orange crowned Warbler', 'Palm Warbler', 'Pine Warbler', 'Prairie Warbler', 'Prothonotary Warbler', 'Swainson Warbler', 'Tennessee Warbler', 'Wilson Warbler', 'Worm eating Warbler', 'Yellow Warbler', 'Northern Waterthrush', 'Louisiana Waterthrush', 'Bohemian Waxwing', 'Cedar Waxwing', 'American Three toed Woodpecker', 'Pileated Woodpecker', 'Red bellied Woodpecker', 'Red cockaded Woodpecker', 'Red headed Woodpecker', 'Downy Woodpecker', 'Bewick Wren', 'Cactus Wren', 'Carolina Wren', 'House Wren', 'Marsh Wren', 'Rock Wren', 'Winter Wren', 'Common Yellowthroat']


def get_images(image_dir):
    img_width, img_height = 224, 224 
    channels = 3
    batch_size = 64
    num_images= 50
    image_arr_size= img_width * img_height * channels
    image_index = 0
    image_arr_size= img_width * img_height * channels
    images = np.ndarray(shape=(num_images, image_arr_size))
    labels = np.array([])                       

    for type in os.listdir(image_dir)[:50]:
        print(type)
        type_images = os.listdir(image_dir + type)
        labels= np.append(labels, type.split('-')[1])

    return (images, labels)

detailed_labels = [
["American_Pipit_0109_99710.jpg a photography of a bird in a field",
"American_Pipit_0010_99843.jpg a photography of a bird perched on a branch",
"American_Pipit_0039_99841.jpg a photography of a bird standing in a puddle",
"American_Pipit_0017_99902.jpg a photography of a bird in a field",
"American_Pipit_0101_100053.jpg a photography of a bird on a rock",
"American_Pipit_0090_99651.jpg a photography of a bird",
"American_Pipit_0058_100218.jpg a photography of a bird in the water",
"American_Pipit_0022_100227.jpg a photography of a bird",
"American_Pipit_0001_100225.jpg a photography of a house sparrow",
"American_Pipit_0116_100015.jpg a photography of a bird in a muddy field",
"American_Pipit_0113_99939.jpg a photography of a bird",
"American_Pipit_0088_100213.jpg a photography of a bird in the grass",
"American_Pipit_0031_99607.jpg a photography of a bird on a rock in the water",
"American_Pipit_0062_100000.jpg a photography of a bird",
"American_Pipit_0006_99857.jpg a photography of a bird on the ground",
"American_Pipit_0080_100055.jpg a photography of a bird on a rocky shore",
"American_Pipit_0034_99946.jpg a photography of a bird on the ground",
"American_Pipit_0066_99961.jpg a photography of a bird",
"American_Pipit_0104_100147.jpg a photography of a bird on a rock",
"American_Pipit_0074_100154.jpg a photography of a bird",
"American_Pipit_0021_100378.jpg a photography of a bird perched on a branch",
"American_Pipit_0073_99642.jpg a photography of a bird",
"American_Pipit_0082_99867.jpg a photography of a bird standing in the mud",
"American_Pipit_0019_99810.jpg a photography of a bird",
"American_Pipit_0123_99929.jpg a photography of a bird on the shore of a lake",
"American_Pipit_0111_99940.jpg a photography of a bird in the grass",
"American_Pipit_0098_99986.jpg a photography of a bird in the grass",
"American_Pipit_0007_99808.jpg a photography of a bird perched on a branch",
"American_Pipit_0089_100260.jpg a photography of a bird in the grass",
"American_Pipit_0048_100140.jpg a photography of a bird on a post"],
["Black_Throated_Sparrow_0081_107111.jpg a photography of a bird on a rock",
"Black_Throated_Sparrow_0023_107104.jpg a photography of a bird on a rock",
"Black_Throated_Sparrow_0065_107087.jpg a photography of a bird sitting on a branch",
"Black_Throated_Sparrow_0068_106960.jpg a photography of a bird",
"Black_Throated_Sparrow_0005_107150.jpg a photography of a bird perched on a cactus",
"Black_Throated_Sparrow_0051_107217.jpg a photography of a bird in the ground",
"Black_Throated_Sparrow_0002_106962.jpg a photography of a bird on a wire",
"Black_Throated_Sparrow_0046_107339.jpg a photography of a bird perched on a tree branch",
"Black_Throated_Sparrow_0053_107282.jpg a photography of a bird in a tree",
"Black_Throated_Sparrow_0033_107042.jpg a photography of a small bird on the ground",
"Black_Throated_Sparrow_0003_107035.jpg a photography of a bird on the ground",
"Black_Throated_Sparrow_0021_107021.jpg a photography of a bird on a tree stump",
"Black_Throated_Sparrow_0039_107259.jpg a photography of a bird",
"Black_Throated_Sparrow_0013_107005.jpg a photography of a bird",
"Black_Throated_Sparrow_0074_107113.jpg a photography of a bird on a branch",
"Black_Throated_Sparrow_0099_106944.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0091_107346.jpg a photography of a bird in a tree",
"Black_Throated_Sparrow_0019_107192.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0026_107198.jpg a photography of a bird perched on a person's hand",
"Black_Throated_Sparrow_0015_107079.jpg a photography of a bird",
"Black_Throated_Sparrow_0060_107177.jpg a photography of a bird on a rocky area",
"Black_Throated_Sparrow_0061_106967.jpg a photography of a bird perched on a dead tree",
"Black_Throated_Sparrow_0080_107050.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0084_107066.jpg a photography of a bird on the ground",
"Black_Throated_Sparrow_0017_107355.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0050_107033.jpg a photography of a bird",
"Black_Throated_Sparrow_0043_107236.jpg a photography of a bird",
"Black_Throated_Sparrow_0102_107243.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0096_107238.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0078_107298.jpg a photography of a bird perched on a branch"],
["Red_Cockaded_Woodpecker_0041_182408.jpg a photography of a bird in a nest",
"Red_Cockaded_Woodpecker_0018_794705.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0025_794710.jpg a photography of a red - bell woodpear",
"Red_Cockaded_Woodpecker_0030_794711.jpg a photography of a pileea woodpearch",
"Red_Cockaded_Woodpecker_0003_794695.jpg a photography of a bird perched on a tree branch",
"Red_Cockaded_Woodpecker_0038_794719.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0042_182373.jpg a photography of a bird in a tree",
"Red_Cockaded_Woodpecker_0027_794713.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0048_182599.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0001_182541.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0020_182683.jpg a photography of a bird perched on a tree",
"Red_Cockaded_Woodpecker_0047_794704.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0040_182502.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0055_182520.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0050_794743.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0034_794720.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0053_794707.jpg a photography of a great spotted woodpeart",
"Red_Cockaded_Woodpecker_0052_794752.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0017_794712.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0037_794733.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0002_794696.jpg a photography of a bird in a tree",
"Red_Cockaded_Woodpecker_0009_182540.jpg a photography of a bird on a tree",
"Red_Cockaded_Woodpecker_0059_794709.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0060_182377.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0014_794718.jpg a photography of a bird perched on a tree",
"Red_Cockaded_Woodpecker_0013_794740.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0028_182395.jpg a photography of a bird perched on a tree",
"Red_Cockaded_Woodpecker_0023_794701.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0063_794726.jpg a photography of a bird on a tree"],
["Vesper_Sparrow_0094_125602.jpg a photography of a bird perched on a wooden post",
"Vesper_Sparrow_0032_125564.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0031_125631.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0005_125440.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0020_125794.jpg a photography of a bird in the grass",
"Vesper_Sparrow_0066_125619.jpg a photography of a bird perched on a stump",
"Vesper_Sparrow_0003_125427.jpg a photography of a bird in the grass",
"Vesper_Sparrow_0058_125661.jpg a photography of a bird on a wire fence",
"Vesper_Sparrow_0028_118217.jpg a photography of a bird on a fence post",
"Vesper_Sparrow_0041_125458.jpg a photography of a bird on a branch",
"Vesper_Sparrow_0091_125598.jpg a photography of a bird perched on a branch",
"Vesper_Sparrow_0086_125776.jpg a photography of a bird on a barbed fence",
"Vesper_Sparrow_0080_125606.jpg a photography of a bird on the ground",
"Vesper_Sparrow_0011_125608.jpg a photography of a bird eating corn",
"Vesper_Sparrow_0077_125597.jpg a photography of a bird on a gravel road",
"Vesper_Sparrow_0047_125788.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0068_125601.jpg a photography of a bird",
"Vesper_Sparrow_0033_125568.jpg a photography of a bird",
"Vesper_Sparrow_0045_125643.jpg a photography of a bird",
"Vesper_Sparrow_0056_125657.jpg a photography of a bird perched on a tree branch",
"Vesper_Sparrow_0049_125806.jpg a photography of a bird",
"Vesper_Sparrow_0030_125663.jpg a photography of a bird",
"Vesper_Sparrow_0013_109937.jpg a photography of a bird perched on a branch",
"Vesper_Sparrow_0067_125429.jpg a photography of a bird on a wire fence",
"Vesper_Sparrow_0022_125719.jpg a photography of a bird on a plant",
"Vesper_Sparrow_0015_125653.jpg a photography of a bird",
"Vesper_Sparrow_0009_125713.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0057_125649.jpg a photography of a bird",
"Vesper_Sparrow_0052_125444.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0040_125441.jpg a photography of a bird on a wooden fence"],
["Worm_Eating_Warbler_0018_795546.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0060_175969.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0036_795573.jpg a photography of a bird",
"Worm_Eating_Warbler_0019_795554.jpg a photography of a yellow warbler",
"Worm_Eating_Warbler_0063_795553.jpg a photography of a bird perched on a hand",
"Worm_Eating_Warbler_0054_176130.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0057_176006.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0002_795533.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0023_176118.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0101_795557.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0006_176037.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0045_795518.jpg a photography of a yellow - crowned warbler",
"Worm_Eating_Warbler_0098_795565.jpg a photography of a goldfinch",
"Worm_Eating_Warbler_0062_795568.jpg a photography of a bird in the woods",
"Worm_Eating_Warbler_0066_92460.jpg a photography of a bird",
"Worm_Eating_Warbler_0051_176068.jpg a photography of a bird",
"Worm_Eating_Warbler_0085_795540.jpg a photography of a bird",
"Worm_Eating_Warbler_0076_176086.jpg a photography of a bird in the grass",
"Worm_Eating_Warbler_0022_176111.jpg a photography of a bird in a tree",
"Worm_Eating_Warbler_0086_176073.jpg a photography of a bird",
"Worm_Eating_Warbler_0102_176069.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0072_795559.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0049_795561.jpg a photography of a bird perched on a tree branch",
"Worm_Eating_Warbler_0012_795515.jpg a photography of a bird singing on a branch",
"Worm_Eating_Warbler_0079_176036.jpg a photography of a bird",
"Worm_Eating_Warbler_0042_795571.jpg a photography of a bird eating on a seed",
"Worm_Eating_Warbler_0031_176075.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0090_795523.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0092_795524.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0078_795532.jpg a photography of a bird"],
["House_Wren_0004_187448.jpg a photography of a bird perched on a branch",
"House_Wren_0034_187120.jpg a photography of a bird perched on a wooden post",
"House_Wren_0137_187273.jpg a photography of a bird",
"House_Wren_0090_187762.jpg a photography of a bird",
"House_Wren_0091_188046.jpg a photography of a bird perched on a branch",
"House_Wren_0035_187708.jpg a photography of a bird eating on a piece of wood",
"House_Wren_0055_187397.jpg a photography of a small bird perched on a leaf",
"House_Wren_0123_187095.jpg a photography of a bird on a rusty fence",
"House_Wren_0043_187224.jpg a photography of a bird eating a piece of food",
"House_Wren_0011_187547.jpg a photography of a bird perched on a branch",
"House_Wren_0118_187383.jpg a photography of a bird perched on a branch",
"House_Wren_0072_187899.jpg a photography of a bird perched on a fence post",
"House_Wren_0116_187604.jpg a photography of a bird",
"House_Wren_0129_187376.jpg a photography of a bird",
"House_Wren_0099_187240.jpg a photography of a bird perched on a branch",
"House_Wren_0094_187226.jpg a photography of a bird perched on a branch",
"House_Wren_0134_188077.jpg a photography of a bird perched on a branch",
"House_Wren_0042_187098.jpg a photography of a bird on a wall",
"House_Wren_0016_188006.jpg a photography of a bird perched on a branch",
"House_Wren_0097_187760.jpg a photography of a house wren",
"House_Wren_0110_187111.jpg a photography of a bird",
"House_Wren_0107_187230.jpg a photography of a bird",
"House_Wren_0086_187815.jpg a photography of a bird",
"House_Wren_0047_188036.jpg a photography of a bird on a branch",
"House_Wren_0083_187406.jpg a photography of a bird in a tree",
"House_Wren_0112_187355.jpg a photography of a bird on a tree",
"House_Wren_0114_188016.jpg a photography of a bird perched on a branch",
"House_Wren_0092_187100.jpg a photography of a bird on a branch",
"House_Wren_0071_187399.jpg a photography of a bird perched on a branch of a tree",
"House_Wren_0045_187374.jpg a photography of a bird"],
["Pine_Grosbeak_0050_38475.jpg a photography of a bird",
"Pine_Grosbeak_0049_38380.jpg a photography of a male northern cardinal",
"Pine_Grosbeak_0115_38330.jpg a photography of a bird in a tree with berries",
"Pine_Grosbeak_0004_38396.jpg a photography of a bird",
"Pine_Grosbeak_0053_38805.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0056_38940.jpg a photography of a bird eating on a branch",
"Pine_Grosbeak_0019_38845.jpg a photography of a bird on a bird bath",
"Pine_Grosbeak_0111_38741.jpg a photography of a bird in the leaves",
"Pine_Grosbeak_0003_38437.jpg a photography of a bird",
"Pine_Grosbeak_0097_38735.jpg a photography of a bird on a branch with berries",
"Pine_Grosbeak_0106_38218.jpg a photography of a bird perched on a tree branch",
"Pine_Grosbeak_0043_38992.jpg a photography of a bird",
"Pine_Grosbeak_0071_38207.jpg a photography of a bird",
"Pine_Grosbeak_0029_38995.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0068_38981.jpg a photography of a bird on a branch",
"Pine_Grosbeak_0014_38398.jpg a photography of a bird on a bird feeder",
"Pine_Grosbeak_0008_38486.jpg a photography of a bird",
"Pine_Grosbeak_0021_38382.jpg a photography of a male cardinal bird in a tree with red berries",
"Pine_Grosbeak_0104_38362.jpg a photography of a bird",
"Pine_Grosbeak_0044_38766.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0082_38552.jpg a photography of a bird",
"Pine_Grosbeak_0096_38441.jpg a photography of a bird",
"Pine_Grosbeak_0107_38351.jpg a photography of a bird perched on a branch of a tree",
"Pine_Grosbeak_0018_38374.jpg a photography of a bird",
"Pine_Grosbeak_0055_38730.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0048_38434.jpg a photography of a bird perched on a tree",
"Pine_Grosbeak_0033_38945.jpg a photography of a bird eating berries from a tree",
"Pine_Grosbeak_0109_38451.jpg a photography of a red bird perched on a branch of a tree",
"Pine_Grosbeak_0100_38988.jpg a photography of a bird eating on a branch",
"Pine_Grosbeak_0024_38403.jpg a photography of a bird perched on a branch"],
["Philadelphia_Vireo_0001_156554.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0039_794794.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0030_156533.jpg a photography of a bird",
"Philadelphia_Vireo_0029_794760.jpg a photography of a bird",
"Philadelphia_Vireo_0027_156585.jpg a photography of a bird on a branch",
"Philadelphia_Vireo_0062_794777.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0034_794766.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0003_156565.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0061_156613.jpg a photography of a bird",
"Philadelphia_Vireo_0013_794772.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0060_156555.jpg a photography of a bird",
"Philadelphia_Vireo_0010_794769.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0015_794778.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0083_794761.jpg a photography of a bird in the grass",
"Philadelphia_Vireo_0023_794797.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0082_156574.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0067_156584.jpg a photography of a bird",
"Philadelphia_Vireo_0024_156645.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0078_794776.jpg a photography of a bird in a tree",
"Philadelphia_Vireo_0040_794764.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0028_156510.jpg a photography of a female white - eye bird",
"Philadelphia_Vireo_0007_156617.jpg a photography of a bird in a tree",
"Philadelphia_Vireo_0012_794785.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0057_156525.jpg a photography of a bird",
"Philadelphia_Vireo_0045_156608.jpg a photography of a bird in a tree",
"Philadelphia_Vireo_0050_156538.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0037_794770.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0049_794756.jpg a photography of a bird",
"Philadelphia_Vireo_0084_794790.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0044_156548.jpg a photography of a bird perched on a branch"],
["European_Goldfinch_0062_794657.jpg a photography of a bird",
"European_Goldfinch_0106_33298.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0037_33149.jpg a photography of a male goldfinch",
"European_Goldfinch_0008_33153.jpg a photography of a bird",
"European_Goldfinch_0090_794648.jpg a photography of a male goldfinch in the rainforest of the daie island",
"European_Goldfinch_0014_794672.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0045_794690.jpg a photography of a bird in the grass",
"European_Goldfinch_0068_33359.jpg a photography of a bird on a wire",
"European_Goldfinch_0032_794679.jpg a photography of a bird",
"European_Goldfinch_0004_33313.jpg a photography of a bird on a branch",
"European_Goldfinch_0046_33307.jpg a photography of a bird",
"European_Goldfinch_0054_33169.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0003_33066.jpg a photography of a bird",
"European_Goldfinch_0020_794644.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0041_794645.jpg a photography of a goldfinch perched on a thistle plant",
"European_Goldfinch_0085_794682.jpg a photography of a bird",
"European_Goldfinch_0034_33256.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0076_33173.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0088_794651.jpg a photography of a goldfinch",
"European_Goldfinch_0025_794647.jpg a photography of a male goldfinch in a tree",
"European_Goldfinch_0047_33332.jpg a photography of a bird on a bird feeder",
"European_Goldfinch_0093_794653.jpg a photography of a male goldfinch",
"European_Goldfinch_0048_794656.jpg a photography of a bird",
"European_Goldfinch_0097_794688.jpg a photography of a bird in flight",
"European_Goldfinch_0006_794661.jpg a photography of a male goldfinch",
"European_Goldfinch_0011_794676.jpg a photography of a male great tira",
"European_Goldfinch_0058_794665.jpg a photography of a bird perched on a barbed fence",
"European_Goldfinch_0081_33259.jpg a photography of a bird perched on a thistle plant",
"European_Goldfinch_0053_794639.jpg a photography of a bird",
"European_Goldfinch_0078_33170.jpg a photography of a bird"]
]

ln = [len(detailed_labels[i])for i in range(9)]
print(ln)