import zipfile
import os
import numpy as np

# extraction zip
#zip_path = "/home/onyxia/work/datasets/stanford_cars.zip"
#with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#    zip_ref.extractall("/home/onyxia/work/datasets")

checkpoint_path = 'python DetailCLIP/eval_zeroshot.py --resume /home/onyxia/work/DetailCLIP/checkpoint_best.pt'

timm_path = '/usr/local/lib/python3.12/site-packages/timm/models'

dataset_path = "/home/onyxia/work/datasets/split_CUB200_2011/test"
#titles = [d for d in os.listdir(dataset_path) if os.path.isdir(os.path.join(dataset_path, d))]
#titles.sort()
titles = ['Black footed Albatross', 'Laysan Albatross', 'Sooty Albatross', 'Groove billed Ani', 'Crested Auklet', 'Least Auklet', 'Parakeet Auklet', 'Rhinoceros Auklet', 'Brewer Blackbird', 'Red winged Blackbird', 'Rusty Blackbird', 'Yellow headed Blackbird', 'Bobolink', 'Indigo Bunting', 'Lazuli Bunting', 'Painted Bunting', 'Cardinal', 'Spotted Catbird', 'Gray Catbird', 'Yellow breasted Chat', 'Eastern Towhee', 'Chuck will Widow', 'Brandt Cormorant', 'Red faced Cormorant', 'Pelagic Cormorant', 'Bronzed Cowbird', 'Shiny Cowbird', 'Brown Creeper', 'American Crow', 'Fish Crow', 'Black billed Cuckoo', 'Mangrove Cuckoo', 'Yellow billed Cuckoo', 'Gray crowned Rosy Finch', 'Purple Finch', 'Northern Flicker', 'Acadian Flycatcher', 'Great Crested Flycatcher', 'Least Flycatcher', 'Olive sided Flycatcher', 'Scissor tailed Flycatcher', 'Vermilion Flycatcher', 'Yellow bellied Flycatcher', 'Frigatebird', 'Northern Fulmar', 'Gadwall', 'American Goldfinch', 'European Goldfinch', 'Boat tailed Grackle', 'Eared Grebe', 'Horned Grebe', 'Pied billed Grebe', 'Western Grebe', 'Blue Grosbeak', 'Evening Grosbeak', 'Pine Grosbeak', 'Rose breasted Grosbeak', 'Pigeon Guillemot', 'California Gull', 'Glaucous winged Gull', 'Heermann Gull', 'Herring Gull', 'Ivory Gull', 'Ring billed Gull', 'Slaty backed Gull', 'Western Gull', 'Anna Hummingbird', 'Ruby throated Hummingbird', 'Rufous Hummingbird', 'Green Violetear', 'Long tailed Jaeger', 'Pomarine Jaeger', 'Blue Jay', 'Florida Jay', 'Green Jay', 'Dark eyed Junco', 'Tropical Kingbird', 'Gray Kingbird', 'Belted Kingfisher', 'Green Kingfisher', 'Pied Kingfisher', 'Ringed Kingfisher', 'White breasted Kingfisher', 'Red legged Kittiwake', 'Horned Lark', 'Pacific Loon', 'Mallard', 'Western Meadowlark', 'Hooded Merganser', 'Red breasted Merganser', 'Mockingbird', 'Nighthawk', 'Clark Nutcracker', 'White breasted Nuthatch', 'Baltimore Oriole', 'Hooded Oriole', 'Orchard Oriole', 'Scott Oriole', 'Ovenbird', 'Brown Pelican', 'White Pelican', 'Western Wood Pewee', 'Sayornis', 'American Pipit', 'Whip poor Will', 'Horned Puffin', 'Common Raven', 'White necked Raven', 'American Redstart', 'Geococcyx', 'Loggerhead Shrike', 'Great Grey Shrike', 'Baird Sparrow', 'Black throated Sparrow', 'Brewer Sparrow', 'Chipping Sparrow', 'Clay colored Sparrow', 'House Sparrow', 'Field Sparrow', 'Fox Sparrow', 'Grasshopper Sparrow', 'Harris Sparrow', 'Henslow Sparrow', 'Le Conte Sparrow', 'Lincoln Sparrow', 'Nelson Sharp tailed Sparrow', 'Savannah Sparrow', 'Seaside Sparrow', 'Song Sparrow', 'Tree Sparrow', 'Vesper Sparrow', 'White crowned Sparrow', 'White throated Sparrow', 'Cape Glossy Starling', 'Bank Swallow', 'Barn Swallow', 'Cliff Swallow', 'Tree Swallow', 'Scarlet Tanager', 'Summer Tanager', 'Artic Tern', 'Black Tern', 'Caspian Tern', 'Common Tern', 'Elegant Tern', 'Forsters Tern', 'Least Tern', 'Green tailed Towhee', 'Brown Thrasher', 'Sage Thrasher', 'Black capped Vireo', 'Blue headed Vireo', 'Philadelphia Vireo', 'Red eyed Vireo', 'Warbling Vireo', 'White eyed Vireo', 'Yellow throated Vireo', 'Bay breasted Warbler', 'Black and white Warbler', 'Black throated Blue Warbler', 'Blue winged Warbler', 'Canada Warbler', 'Cape May Warbler', 'Cerulean Warbler', 'Chestnut sided Warbler', 'Golden winged Warbler', 'Hooded Warbler', 'Kentucky Warbler', 'Magnolia Warbler', 'Mourning Warbler', 'Myrtle Warbler', 'Nashville Warbler', 'Orange crowned Warbler', 'Palm Warbler', 'Pine Warbler', 'Prairie Warbler', 'Prothonotary Warbler', 'Swainson Warbler', 'Tennessee Warbler', 'Wilson Warbler', 'Worm eating Warbler', 'Yellow Warbler', 'Northern Waterthrush', 'Louisiana Waterthrush', 'Bohemian Waxwing', 'Cedar Waxwing', 'American Three toed Woodpecker', 'Pileated Woodpecker', 'Red bellied Woodpecker', 'Red cockaded Woodpecker', 'Red headed Woodpecker', 'Downy Woodpecker', 'Bewick Wren', 'Cactus Wren', 'Carolina Wren', 'House Wren', 'Marsh Wren', 'Rock Wren', 'Winter Wren', 'Common Yellowthroat']
short_labels = ['Black footed Albatross', 'Laysan Albatross', 'Sooty Albatross', 'Groove billed Ani', 'Crested Auklet', 'Least Auklet', 'Parakeet Auklet', 'Rhinoceros Auklet', 'Brewer Blackbird', 'Red winged Blackbird', 'Rusty Blackbird', 'Yellow headed Blackbird', 'Bobolink', 'Indigo Bunting', 'Lazuli Bunting', 'Painted Bunting', 'Cardinal', 'Spotted Catbird', 'Gray Catbird', 'Yellow breasted Chat', 'Eastern Towhee', 'Chuck will Widow', 'Brandt Cormorant', 'Red faced Cormorant', 'Pelagic Cormorant', 'Bronzed Cowbird', 'Shiny Cowbird', 'Brown Creeper', 'American Crow', 'Fish Crow', 'Black billed Cuckoo', 'Mangrove Cuckoo', 'Yellow billed Cuckoo', 'Gray crowned Rosy Finch', 'Purple Finch', 'Northern Flicker', 'Acadian Flycatcher', 'Great Crested Flycatcher', 'Least Flycatcher', 'Olive sided Flycatcher', 'Scissor tailed Flycatcher', 'Vermilion Flycatcher', 'Yellow bellied Flycatcher', 'Frigatebird', 'Northern Fulmar', 'Gadwall', 'American Goldfinch', 'European Goldfinch', 'Boat tailed Grackle', 'Eared Grebe', 'Horned Grebe', 'Pied billed Grebe', 'Western Grebe', 'Blue Grosbeak', 'Evening Grosbeak', 'Pine Grosbeak', 'Rose breasted Grosbeak', 'Pigeon Guillemot', 'California Gull', 'Glaucous winged Gull', 'Heermann Gull', 'Herring Gull', 'Ivory Gull', 'Ring billed Gull', 'Slaty backed Gull', 'Western Gull', 'Anna Hummingbird', 'Ruby throated Hummingbird', 'Rufous Hummingbird', 'Green Violetear', 'Long tailed Jaeger', 'Pomarine Jaeger', 'Blue Jay', 'Florida Jay', 'Green Jay', 'Dark eyed Junco', 'Tropical Kingbird', 'Gray Kingbird', 'Belted Kingfisher', 'Green Kingfisher', 'Pied Kingfisher', 'Ringed Kingfisher', 'White breasted Kingfisher', 'Red legged Kittiwake', 'Horned Lark', 'Pacific Loon', 'Mallard', 'Western Meadowlark', 'Hooded Merganser', 'Red breasted Merganser', 'Mockingbird', 'Nighthawk', 'Clark Nutcracker', 'White breasted Nuthatch', 'Baltimore Oriole', 'Hooded Oriole', 'Orchard Oriole', 'Scott Oriole', 'Ovenbird', 'Brown Pelican', 'White Pelican', 'Western Wood Pewee', 'Sayornis', 'American Pipit', 'Whip poor Will', 'Horned Puffin', 'Common Raven', 'White necked Raven', 'American Redstart', 'Geococcyx', 'Loggerhead Shrike', 'Great Grey Shrike', 'Baird Sparrow', 'Black throated Sparrow', 'Brewer Sparrow', 'Chipping Sparrow', 'Clay colored Sparrow', 'House Sparrow', 'Field Sparrow', 'Fox Sparrow', 'Grasshopper Sparrow', 'Harris Sparrow', 'Henslow Sparrow', 'Le Conte Sparrow', 'Lincoln Sparrow', 'Nelson Sharp tailed Sparrow', 'Savannah Sparrow', 'Seaside Sparrow', 'Song Sparrow', 'Tree Sparrow', 'Vesper Sparrow', 'White crowned Sparrow', 'White throated Sparrow', 'Cape Glossy Starling', 'Bank Swallow', 'Barn Swallow', 'Cliff Swallow', 'Tree Swallow', 'Scarlet Tanager', 'Summer Tanager', 'Artic Tern', 'Black Tern', 'Caspian Tern', 'Common Tern', 'Elegant Tern', 'Forsters Tern', 'Least Tern', 'Green tailed Towhee', 'Brown Thrasher', 'Sage Thrasher', 'Black capped Vireo', 'Blue headed Vireo', 'Philadelphia Vireo', 'Red eyed Vireo', 'Warbling Vireo', 'White eyed Vireo', 'Yellow throated Vireo', 'Bay breasted Warbler', 'Black and white Warbler', 'Black throated Blue Warbler', 'Blue winged Warbler', 'Canada Warbler', 'Cape May Warbler', 'Cerulean Warbler', 'Chestnut sided Warbler', 'Golden winged Warbler', 'Hooded Warbler', 'Kentucky Warbler', 'Magnolia Warbler', 'Mourning Warbler', 'Myrtle Warbler', 'Nashville Warbler', 'Orange crowned Warbler', 'Palm Warbler', 'Pine Warbler', 'Prairie Warbler', 'Prothonotary Warbler', 'Swainson Warbler', 'Tennessee Warbler', 'Wilson Warbler', 'Worm eating Warbler', 'Yellow Warbler', 'Northern Waterthrush', 'Louisiana Waterthrush', 'Bohemian Waxwing', 'Cedar Waxwing', 'American Three toed Woodpecker', 'Pileated Woodpecker', 'Red bellied Woodpecker', 'Red cockaded Woodpecker', 'Red headed Woodpecker', 'Downy Woodpecker', 'Bewick Wren', 'Cactus Wren', 'Carolina Wren', 'House Wren', 'Marsh Wren', 'Rock Wren', 'Winter Wren', 'Common Yellowthroat']


def get_images(image_dir):
    img_width, img_height = 224, 224 
    channels = 3
    batch_size = 64
    num_images= 50
    image_arr_size= img_width * img_height * channels
    image_index = 0
    image_arr_size= img_width * img_height * channels
    images = np.ndarray(shape=(num_images, image_arr_size))
    labels = np.array([])                       

    for type in os.listdir(image_dir)[:50]:
        print(type)
        type_images = os.listdir(image_dir + type)
        labels= np.append(labels, type.split('-')[1])

    return (images, labels)

detailed_labels = [
["American_Pipit_0109_99710.jpg a photography of a bird in a field",
"American_Pipit_0010_99843.jpg a photography of a bird perched on a branch",
"American_Pipit_0039_99841.jpg a photography of a bird standing in a puddle",
"American_Pipit_0017_99902.jpg a photography of a bird in a field",
"American_Pipit_0101_100053.jpg a photography of a bird on a rock",
"American_Pipit_0090_99651.jpg a photography of a bird",
"American_Pipit_0058_100218.jpg a photography of a bird in the water",
"American_Pipit_0022_100227.jpg a photography of a bird",
"American_Pipit_0001_100225.jpg a photography of a house sparrow",
"American_Pipit_0116_100015.jpg a photography of a bird in a muddy field",
"American_Pipit_0113_99939.jpg a photography of a bird",
"American_Pipit_0088_100213.jpg a photography of a bird in the grass",
"American_Pipit_0031_99607.jpg a photography of a bird on a rock in the water",
"American_Pipit_0062_100000.jpg a photography of a bird",
"American_Pipit_0006_99857.jpg a photography of a bird on the ground",
"American_Pipit_0080_100055.jpg a photography of a bird on a rocky shore",
"American_Pipit_0034_99946.jpg a photography of a bird on the ground",
"American_Pipit_0066_99961.jpg a photography of a bird",
"American_Pipit_0104_100147.jpg a photography of a bird on a rock",
"American_Pipit_0074_100154.jpg a photography of a bird",
"American_Pipit_0021_100378.jpg a photography of a bird perched on a branch",
"American_Pipit_0073_99642.jpg a photography of a bird",
"American_Pipit_0082_99867.jpg a photography of a bird standing in the mud",
"American_Pipit_0019_99810.jpg a photography of a bird",
"American_Pipit_0123_99929.jpg a photography of a bird on the shore of a lake",
"American_Pipit_0111_99940.jpg a photography of a bird in the grass",
"American_Pipit_0098_99986.jpg a photography of a bird in the grass",
"American_Pipit_0007_99808.jpg a photography of a bird perched on a branch",
"American_Pipit_0089_100260.jpg a photography of a bird in the grass",
"American_Pipit_0048_100140.jpg a photography of a bird on a post"],
["Black_Throated_Sparrow_0081_107111.jpg a photography of a bird on a rock",
"Black_Throated_Sparrow_0023_107104.jpg a photography of a bird on a rock",
"Black_Throated_Sparrow_0065_107087.jpg a photography of a bird sitting on a branch",
"Black_Throated_Sparrow_0068_106960.jpg a photography of a bird",
"Black_Throated_Sparrow_0005_107150.jpg a photography of a bird perched on a cactus",
"Black_Throated_Sparrow_0051_107217.jpg a photography of a bird in the ground",
"Black_Throated_Sparrow_0002_106962.jpg a photography of a bird on a wire",
"Black_Throated_Sparrow_0046_107339.jpg a photography of a bird perched on a tree branch",
"Black_Throated_Sparrow_0053_107282.jpg a photography of a bird in a tree",
"Black_Throated_Sparrow_0033_107042.jpg a photography of a small bird on the ground",
"Black_Throated_Sparrow_0003_107035.jpg a photography of a bird on the ground",
"Black_Throated_Sparrow_0021_107021.jpg a photography of a bird on a tree stump",
"Black_Throated_Sparrow_0039_107259.jpg a photography of a bird",
"Black_Throated_Sparrow_0013_107005.jpg a photography of a bird",
"Black_Throated_Sparrow_0074_107113.jpg a photography of a bird on a branch",
"Black_Throated_Sparrow_0099_106944.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0091_107346.jpg a photography of a bird in a tree",
"Black_Throated_Sparrow_0019_107192.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0026_107198.jpg a photography of a bird perched on a person's hand",
"Black_Throated_Sparrow_0015_107079.jpg a photography of a bird",
"Black_Throated_Sparrow_0060_107177.jpg a photography of a bird on a rocky area",
"Black_Throated_Sparrow_0061_106967.jpg a photography of a bird perched on a dead tree",
"Black_Throated_Sparrow_0080_107050.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0084_107066.jpg a photography of a bird on the ground",
"Black_Throated_Sparrow_0017_107355.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0050_107033.jpg a photography of a bird",
"Black_Throated_Sparrow_0043_107236.jpg a photography of a bird",
"Black_Throated_Sparrow_0102_107243.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0096_107238.jpg a photography of a bird perched on a branch",
"Black_Throated_Sparrow_0078_107298.jpg a photography of a bird perched on a branch"],
["Red_Cockaded_Woodpecker_0041_182408.jpg a photography of a bird in a nest",
"Red_Cockaded_Woodpecker_0018_794705.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0025_794710.jpg a photography of a red - bell woodpear",
"Red_Cockaded_Woodpecker_0030_794711.jpg a photography of a pileea woodpearch",
"Red_Cockaded_Woodpecker_0003_794695.jpg a photography of a bird perched on a tree branch",
"Red_Cockaded_Woodpecker_0038_794719.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0042_182373.jpg a photography of a bird in a tree",
"Red_Cockaded_Woodpecker_0027_794713.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0048_182599.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0001_182541.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0020_182683.jpg a photography of a bird perched on a tree",
"Red_Cockaded_Woodpecker_0047_794704.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0040_182502.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0055_182520.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0050_794743.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0034_794720.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0053_794707.jpg a photography of a great spotted woodpeart",
"Red_Cockaded_Woodpecker_0052_794752.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0017_794712.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0037_794733.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0002_794696.jpg a photography of a bird in a tree",
"Red_Cockaded_Woodpecker_0009_182540.jpg a photography of a bird on a tree",
"Red_Cockaded_Woodpecker_0059_794709.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0060_182377.jpg a photography of a bird",
"Red_Cockaded_Woodpecker_0014_794718.jpg a photography of a bird perched on a tree",
"Red_Cockaded_Woodpecker_0013_794740.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0028_182395.jpg a photography of a bird perched on a tree",
"Red_Cockaded_Woodpecker_0023_794701.jpg a photography of a woodpeart",
"Red_Cockaded_Woodpecker_0063_794726.jpg a photography of a bird on a tree"],
["Vesper_Sparrow_0094_125602.jpg a photography of a bird perched on a wooden post",
"Vesper_Sparrow_0032_125564.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0031_125631.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0005_125440.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0020_125794.jpg a photography of a bird in the grass",
"Vesper_Sparrow_0066_125619.jpg a photography of a bird perched on a stump",
"Vesper_Sparrow_0003_125427.jpg a photography of a bird in the grass",
"Vesper_Sparrow_0058_125661.jpg a photography of a bird on a wire fence",
"Vesper_Sparrow_0028_118217.jpg a photography of a bird on a fence post",
"Vesper_Sparrow_0041_125458.jpg a photography of a bird on a branch",
"Vesper_Sparrow_0091_125598.jpg a photography of a bird perched on a branch",
"Vesper_Sparrow_0086_125776.jpg a photography of a bird on a barbed fence",
"Vesper_Sparrow_0080_125606.jpg a photography of a bird on the ground",
"Vesper_Sparrow_0011_125608.jpg a photography of a bird eating corn",
"Vesper_Sparrow_0077_125597.jpg a photography of a bird on a gravel road",
"Vesper_Sparrow_0047_125788.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0068_125601.jpg a photography of a bird",
"Vesper_Sparrow_0033_125568.jpg a photography of a bird",
"Vesper_Sparrow_0045_125643.jpg a photography of a bird",
"Vesper_Sparrow_0056_125657.jpg a photography of a bird perched on a tree branch",
"Vesper_Sparrow_0049_125806.jpg a photography of a bird",
"Vesper_Sparrow_0030_125663.jpg a photography of a bird",
"Vesper_Sparrow_0013_109937.jpg a photography of a bird perched on a branch",
"Vesper_Sparrow_0067_125429.jpg a photography of a bird on a wire fence",
"Vesper_Sparrow_0022_125719.jpg a photography of a bird on a plant",
"Vesper_Sparrow_0015_125653.jpg a photography of a bird",
"Vesper_Sparrow_0009_125713.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0057_125649.jpg a photography of a bird",
"Vesper_Sparrow_0052_125444.jpg a photography of a bird on a wire",
"Vesper_Sparrow_0040_125441.jpg a photography of a bird on a wooden fence"],
["Worm_Eating_Warbler_0018_795546.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0060_175969.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0036_795573.jpg a photography of a bird",
"Worm_Eating_Warbler_0019_795554.jpg a photography of a yellow warbler",
"Worm_Eating_Warbler_0063_795553.jpg a photography of a bird perched on a hand",
"Worm_Eating_Warbler_0054_176130.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0057_176006.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0002_795533.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0023_176118.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0101_795557.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0006_176037.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0045_795518.jpg a photography of a yellow - crowned warbler",
"Worm_Eating_Warbler_0098_795565.jpg a photography of a goldfinch",
"Worm_Eating_Warbler_0062_795568.jpg a photography of a bird in the woods",
"Worm_Eating_Warbler_0066_92460.jpg a photography of a bird",
"Worm_Eating_Warbler_0051_176068.jpg a photography of a bird",
"Worm_Eating_Warbler_0085_795540.jpg a photography of a bird",
"Worm_Eating_Warbler_0076_176086.jpg a photography of a bird in the grass",
"Worm_Eating_Warbler_0022_176111.jpg a photography of a bird in a tree",
"Worm_Eating_Warbler_0086_176073.jpg a photography of a bird",
"Worm_Eating_Warbler_0102_176069.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0072_795559.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0049_795561.jpg a photography of a bird perched on a tree branch",
"Worm_Eating_Warbler_0012_795515.jpg a photography of a bird singing on a branch",
"Worm_Eating_Warbler_0079_176036.jpg a photography of a bird",
"Worm_Eating_Warbler_0042_795571.jpg a photography of a bird eating on a seed",
"Worm_Eating_Warbler_0031_176075.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0090_795523.jpg a photography of a bird perched on a branch",
"Worm_Eating_Warbler_0092_795524.jpg a photography of a bird on a branch",
"Worm_Eating_Warbler_0078_795532.jpg a photography of a bird"],
["House_Wren_0004_187448.jpg a photography of a bird perched on a branch",
"House_Wren_0034_187120.jpg a photography of a bird perched on a wooden post",
"House_Wren_0137_187273.jpg a photography of a bird",
"House_Wren_0090_187762.jpg a photography of a bird",
"House_Wren_0091_188046.jpg a photography of a bird perched on a branch",
"House_Wren_0035_187708.jpg a photography of a bird eating on a piece of wood",
"House_Wren_0055_187397.jpg a photography of a small bird perched on a leaf",
"House_Wren_0123_187095.jpg a photography of a bird on a rusty fence",
"House_Wren_0043_187224.jpg a photography of a bird eating a piece of food",
"House_Wren_0011_187547.jpg a photography of a bird perched on a branch",
"House_Wren_0118_187383.jpg a photography of a bird perched on a branch",
"House_Wren_0072_187899.jpg a photography of a bird perched on a fence post",
"House_Wren_0116_187604.jpg a photography of a bird",
"House_Wren_0129_187376.jpg a photography of a bird",
"House_Wren_0099_187240.jpg a photography of a bird perched on a branch",
"House_Wren_0094_187226.jpg a photography of a bird perched on a branch",
"House_Wren_0134_188077.jpg a photography of a bird perched on a branch",
"House_Wren_0042_187098.jpg a photography of a bird on a wall",
"House_Wren_0016_188006.jpg a photography of a bird perched on a branch",
"House_Wren_0097_187760.jpg a photography of a house wren",
"House_Wren_0110_187111.jpg a photography of a bird",
"House_Wren_0107_187230.jpg a photography of a bird",
"House_Wren_0086_187815.jpg a photography of a bird",
"House_Wren_0047_188036.jpg a photography of a bird on a branch",
"House_Wren_0083_187406.jpg a photography of a bird in a tree",
"House_Wren_0112_187355.jpg a photography of a bird on a tree",
"House_Wren_0114_188016.jpg a photography of a bird perched on a branch",
"House_Wren_0092_187100.jpg a photography of a bird on a branch",
"House_Wren_0071_187399.jpg a photography of a bird perched on a branch of a tree",
"House_Wren_0045_187374.jpg a photography of a bird"],
["Pine_Grosbeak_0050_38475.jpg a photography of a bird",
"Pine_Grosbeak_0049_38380.jpg a photography of a male northern cardinal",
"Pine_Grosbeak_0115_38330.jpg a photography of a bird in a tree with berries",
"Pine_Grosbeak_0004_38396.jpg a photography of a bird",
"Pine_Grosbeak_0053_38805.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0056_38940.jpg a photography of a bird eating on a branch",
"Pine_Grosbeak_0019_38845.jpg a photography of a bird on a bird bath",
"Pine_Grosbeak_0111_38741.jpg a photography of a bird in the leaves",
"Pine_Grosbeak_0003_38437.jpg a photography of a bird",
"Pine_Grosbeak_0097_38735.jpg a photography of a bird on a branch with berries",
"Pine_Grosbeak_0106_38218.jpg a photography of a bird perched on a tree branch",
"Pine_Grosbeak_0043_38992.jpg a photography of a bird",
"Pine_Grosbeak_0071_38207.jpg a photography of a bird",
"Pine_Grosbeak_0029_38995.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0068_38981.jpg a photography of a bird on a branch",
"Pine_Grosbeak_0014_38398.jpg a photography of a bird on a bird feeder",
"Pine_Grosbeak_0008_38486.jpg a photography of a bird",
"Pine_Grosbeak_0021_38382.jpg a photography of a male cardinal bird in a tree with red berries",
"Pine_Grosbeak_0104_38362.jpg a photography of a bird",
"Pine_Grosbeak_0044_38766.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0082_38552.jpg a photography of a bird",
"Pine_Grosbeak_0096_38441.jpg a photography of a bird",
"Pine_Grosbeak_0107_38351.jpg a photography of a bird perched on a branch of a tree",
"Pine_Grosbeak_0018_38374.jpg a photography of a bird",
"Pine_Grosbeak_0055_38730.jpg a photography of a bird perched on a branch",
"Pine_Grosbeak_0048_38434.jpg a photography of a bird perched on a tree",
"Pine_Grosbeak_0033_38945.jpg a photography of a bird eating berries from a tree",
"Pine_Grosbeak_0109_38451.jpg a photography of a red bird perched on a branch of a tree",
"Pine_Grosbeak_0100_38988.jpg a photography of a bird eating on a branch",
"Pine_Grosbeak_0024_38403.jpg a photography of a bird perched on a branch"],
["Philadelphia_Vireo_0001_156554.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0039_794794.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0030_156533.jpg a photography of a bird",
"Philadelphia_Vireo_0029_794760.jpg a photography of a bird",
"Philadelphia_Vireo_0027_156585.jpg a photography of a bird on a branch",
"Philadelphia_Vireo_0062_794777.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0034_794766.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0003_156565.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0061_156613.jpg a photography of a bird",
"Philadelphia_Vireo_0013_794772.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0060_156555.jpg a photography of a bird",
"Philadelphia_Vireo_0010_794769.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0015_794778.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0083_794761.jpg a photography of a bird in the grass",
"Philadelphia_Vireo_0023_794797.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0082_156574.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0067_156584.jpg a photography of a bird",
"Philadelphia_Vireo_0024_156645.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0078_794776.jpg a photography of a bird in a tree",
"Philadelphia_Vireo_0040_794764.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0028_156510.jpg a photography of a female white - eye bird",
"Philadelphia_Vireo_0007_156617.jpg a photography of a bird in a tree",
"Philadelphia_Vireo_0012_794785.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0057_156525.jpg a photography of a bird",
"Philadelphia_Vireo_0045_156608.jpg a photography of a bird in a tree",
"Philadelphia_Vireo_0050_156538.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0037_794770.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0049_794756.jpg a photography of a bird",
"Philadelphia_Vireo_0084_794790.jpg a photography of a bird perched on a branch",
"Philadelphia_Vireo_0044_156548.jpg a photography of a bird perched on a branch"],
["European_Goldfinch_0062_794657.jpg a photography of a bird",
"European_Goldfinch_0106_33298.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0037_33149.jpg a photography of a male goldfinch",
"European_Goldfinch_0008_33153.jpg a photography of a bird",
"European_Goldfinch_0090_794648.jpg a photography of a male goldfinch in the rainforest of the daie island",
"European_Goldfinch_0014_794672.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0045_794690.jpg a photography of a bird in the grass",
"European_Goldfinch_0068_33359.jpg a photography of a bird on a wire",
"European_Goldfinch_0032_794679.jpg a photography of a bird",
"European_Goldfinch_0004_33313.jpg a photography of a bird on a branch",
"European_Goldfinch_0046_33307.jpg a photography of a bird",
"European_Goldfinch_0054_33169.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0003_33066.jpg a photography of a bird",
"European_Goldfinch_0020_794644.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0041_794645.jpg a photography of a goldfinch perched on a thistle plant",
"European_Goldfinch_0085_794682.jpg a photography of a bird",
"European_Goldfinch_0034_33256.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0076_33173.jpg a photography of a bird perched on a branch",
"European_Goldfinch_0088_794651.jpg a photography of a goldfinch",
"European_Goldfinch_0025_794647.jpg a photography of a male goldfinch in a tree",
"European_Goldfinch_0047_33332.jpg a photography of a bird on a bird feeder",
"European_Goldfinch_0093_794653.jpg a photography of a male goldfinch",
"European_Goldfinch_0048_794656.jpg a photography of a bird",
"European_Goldfinch_0097_794688.jpg a photography of a bird in flight",
"European_Goldfinch_0006_794661.jpg a photography of a male goldfinch",
"European_Goldfinch_0011_794676.jpg a photography of a male great tira",
"European_Goldfinch_0058_794665.jpg a photography of a bird perched on a barbed fence",
"European_Goldfinch_0081_33259.jpg a photography of a bird perched on a thistle plant",
"European_Goldfinch_0053_794639.jpg a photography of a bird",
"European_Goldfinch_0078_33170.jpg a photography of a bird"]
]

ln = [len(detailed_labels[i])for i in range(9)]
print(ln)

detailed = ["a bird standing on a log in the grass.",
"a bird perched on a tree branch with a blue sky in the background.",
"a bird standing in a puddle of water.",
"a bird standing in the grass looking at the camera.",
"a small bird standing on a rock in the grass.",
"a small bird standing on a pile of sticks.",
"a bird standing in the water looking for food.",
"a bird with a worm in its mouth.",
"a bird standing on top of dry grass.",
"a bird standing on the ground next to a body of water.",
"a small bird standing on the ground on a beach.",
"a small bird standing in the grass.",
"a bird sitting on a rock in the water.",
"a small bird standing on the ground in the dirt.",
"a bird standing on a log in the mud.",
"a bird standing on a rock near the water.",
"a bird standing in a puddle of water.",
"a small bird standing on the ground in the grass.",
"a bird standing on a rock in the middle of a field.",
"a bird standing on a rock in the water.",
"a bird in a tree.",
"a small bird standing on top of a muddy ground.",
"a small bird standing on the mud by the water.",
"a small bird standing on the snow in the snow.",
"a small bird standing on the ground near the water.",
"a bird standing in the grass with a puddle of water.",
"a small brown bird in the grass.",
"a female house sparrow sitting on a tree branch in the early morning light.",
"a small bird standing on a dirt patch.",
"a bird sitting on a post in the middle of a field.",
"a small bird on a rock.",
"a bird is sitting on a rock with a picture of it.",
"a bird sitting on a branch in a bush.",
"a bird is standing on a branch in the sun.",
"a bird perched on a branch.",
"a small bird standing on a dirt field.",
"a bird sitting on top of a barbed wire fence.",
"a bird perched on a tree branch with a sky background.",
"a bird perched on top of a tree branch.",
"a small bird standing on the ground in the dirt.",
"a bird sitting on the ground in the middle of the park.",
"a bird perched on top of a dead tree.",
"a small bird standing on the ground in the sand.",
"a bird perched on a branch with a beak open.",
"a bird perched on a branch with a beak open.",
"a bird sitting on a branch of a tree.",
"a bird is perched on a plant in a tree.",
"a bird perched on a branch with a blurry background.",
"a bird is sitting on a person ' s hand.",
"a bird standing on the ground with rocks in the background.",
"a bird standing on a rock in the dirt.",
"a bird perched on a tree branch.",
"a bird perched on a branch of a tree.",
"a bird standing on the ground in the middle of a field.",
"a bird perched on a branch in a tree.",
"a bird perched on a branch.",
"a bird standing on a rock in the dirt.",
"a bird perched on a tree branch.",
"a bird perched on a branch with a blurry background.",
"a bird perched on a flower on a stem.",
"a male woodpecker takes a break from eating a nest in a tree.",
"a woodpecker is perched on a tree stump.",
"a bird is sitting in a hole in a tree.",
"a bird is perched on a tree trunk.",
"a bird is perched on a tree branch.",
"a woodpecker is perched on a tree.",
"a woodpecker with a hole in its beak.",
"a bird of prey in flight.",
"a woodpecker on a tree trunk.",
"a woodpecker building a nest in a tree.",
"a bird perched on a tree branch.",
"biological species feeding on a bird feeder.",
"a woodpecker is perched on a tree.",
"a bird perched on a tree branch.",
"a woodpecker on a tree trunk.",
"a woodpecker sitting on a tree in the middle of a pine forest.",
"a male woodpecker on a tree branch.",
"a woodpecker perched on a tree trunk.",
"a woodpecker perched on a rock in the middle of the desert.",
"a woodpecker on a tree stump.",
"a woodpecker on a tree.",
"a woodpecker perched on a tree trunk.",
"a woodpecker on a tree trunk.",
"a woodpecker checks out a hole in a tree.",
"a bird on a tree branch.",
"a woodpecker on a tree trunk.",
"a woodpecker on a tree trunk.",
"a woodpecker on a tree trunk.",
"a woodpecker on a tree.",
"a bird on a fence post in the middle of nowhere.",
"a bird sitting on a barbed wire fence.",
"a small brown bird sitting on top of a wire.",
"a bird perched on a wire with yellow flowers in the background.",
"a bird is standing in the grass and looking at the camera.",
"a small brown and white bird standing on a piece of wood.",
"a bird in the grass.",
"a bird sitting on a barbed wire fence.",
"a female house sparrow on a fence post in the middle of the desert.",
"a small bird perched on a branch.",
"a bird perched on a branch in a tree.",
"a sparrow sitting on a barbed wire fence.",
"a small bird standing on the ground near grass.",
"a bird is standing on the ground near corn.",
"a bird standing on the ground in the desert.",
"a small bird sitting on a wire with a green background.",
"a bird sitting on the ground in a field.",
"a bird sitting on a fence post in a field.",
"a bird standing on a pile of sticks in the grass.",
"a bird is sitting on a bush in the desert.",
"a bird is sitting on a hand.",
"a small bird perched on top of a log.",
"a bird perched on top of a pine tree branch.",
"a bird is perched on a wire fence.",
"a bird on a flower.",
"a bird sitting in a pile of straw.",
"a bird sitting on a barbed wire fence.",
"a bird perched on a branch of a tree.",
"a bird sitting on a barbed wire fence.",
"a small bird sitting on a wooden bench.",
"a small bird perched on a branch.",
"a bird perched on a branch in a forest.",
"a male house sparrow in the forest.",
"a small bird perched on a branch in the woods.",
"a small bird sitting on a person ' s hand.",
"a bird sitting on a branch in a tree.",
"a bird perched on a branch of a tree.",
"a bird perched on a branch in a tree.",
"a small bird standing on a branch in the forest.",
"a bird perched on a branch of a tree.",
"a small bird perched on a branch of a tree.",
"a bird on a pine cone.",
"a small bird perched on a branch.",
"a small bird standing on the ground in the woods.",
"a small bird standing on a rock near a tree.",
"a bird in a tree.",
"a female house sparrow feeding on a plant in the garden of the royal botanic gardens.",
"a small bird standing in the grass looking around.",
"a small bird in a tree.",
"a bird sitting in a tree.",
"a small bird perched on a branch.",
"a small bird perched on a branch in a forest.",
"a bird sitting on a tree branch in a tree.",
"a small bird perched on a branch with a beak.",
"a small bird perched on a branch of a tree.",
"a small bird standing on a rock near a plant.",
"a small bird perched on a branch in the forest.",
"a bird perched on a branch with a leaf in its beak.",
"a bird is standing on a branch in the leaves.",
"a bird sitting on a tree branch with a bunch of bananas.",
"a bird sitting on a branch in a tree.",
"a bird perched on a telephone pole in the garden of a house in the village of la crosse, in the south of france.",
"a bird perched on a branch in a tree.",
"a bird is sitting on a bird feeder.",
"a bird perched on a branch with a blurry background.",
"a bird standing on a wooden ledge next to a cage.",
"a bird sitting on a leaf of a plant.",
"a bird is perched on a rusty metal fence.",
"a bird on a tree branch.",
"a bird sitting on a branch in a tree.",
"a small brown bird sitting on a branch.",
"a small bird perched on a branch.",
"a bird perched on a branch.",
"a small bird perched on a tree branch.",
"a bird perched on a branch.",
"a small bird perched on a branch of a tree.",
"a small bird perched on a branch in a tree.",
"a bird perched on top of a shoe on a wall.",
"a small bird perched on a branch of a tree.",
"a small bird perched on a stone on a sunny day.",
"a small bird standing on a fence post.",
"a bird perched on a white post.",
"a bird with a long beak standing on a branch.",
"a small bird sitting on a branch in the sun.",
"a bird perched on a branch of a tree.",
"a bird perched on a tree branch next to a tree.",
"a bird perched on a branch.",
"a small bird perched on a branch in the grass.",
"a bird perched on a branch of a tree.",
"a bird perched on a tree stump.",
"biological species in the snow.",
"biological species in the snow.",
"a bird sits on a tree branch with berries.",
"biological species in the snow.",
"biological species is a native.",
"a bird eating a berry in a tree.",
"a bird sitting on a wooden fence.",
"red - bellied woodpecker in water.",
"a bird sits on a branch of a tree with red berries.",
"a bird eating berries on a tree branch.",
"a bird perched on a branch in a tree.",
"a bird sitting on a branch with berries.",
"biological species in the snow.",
"a red bird perched on a pine tree branch.",
"biological species on a branch.",
"a red and black bird on a bird feeder.",
"biological species on a pine tree.",
"a male red - winged blackbird in a tree.",
"a red bird perched on a post.",
"a male house finch perches on a branch in a tree.",
"a bird sitting on the ground in the snow.",
"biological species in the snow.",
"a bird sitting on a branch with berries.",
"a red and black bird perched on a branch.",
"a bird perched on a branch in a tree.",
"a red and black bird sitting on a branch.",
"a bird sitting on a branch with red berries.",
"a bird sitting on a branch with berries.",
"a bird perched on a branch with berries.",
"a red bird perched on a branch.",
"a small bird sitting on a branch in a tree.",
"a small bird sitting on a branch in a tree.",
"a small bird perched on a branch.",
"a bird sitting on a person ' s hand.",
"a yellow bird with a blue band around its neck.",
"a bird sitting on a tree branch.",
"a bird perched on a branch in a tree.",
"a small bird perched on a branch in a tree.",
"a small bird sitting on a branch in a tree.",
"a bird perched on a branch in a tree.",
"a small bird sitting on a branch.",
"a bird sitting on a tree branch with leaves.",
"a bird is sitting on a tree branch.",
"a bird sitting on a nest in a bush.",
"a bird sitting on a branch in a tree.",
"a small bird sitting on a tree branch.",
"a bird sitting on a branch in a tree.",
"a bird perched on a branch of a tree.",
"a bird sitting on a tree branch in a tree.",
"a bird sitting on a branch in a tree.",
"a bird perched on a branch of a tree.",
"a bird sitting on a branch of a tree.",
"a small bird perched on a branch.",
"a bird sitting on a branch in a tree.",
"a bird sitting on a branch in a tree.",
"a bird sitting on a branch in a tree.",
"a bird perched on a branch.",
"a female bird in the palm of my hand.",
"a bird perched on a branch in a tree.",
"a yellow and gray bird perched on a branch.",
"a bird standing on a wet ground next to a puddle.",
"a bird perched on a twig with a blurry background.",
"biological species is a bird of the species.",
"a bird perched on a branch with leaves.",
"a bird with a long beak standing on a tree branch.",
"a bird with a red head and black head and yellow head.",
"a male goldfinch eating a fish in the grass.",
"a bird perched on a barbed wire fence.",
"a bird in my hand. i think it ' s a bird of a bird that i have seen in my house.",
"a bird on a branch with leaves.",
"a bird with a yellow head and black head and black eyes.",
"a bird perched on a branch in a tree.",
"a bird with a yellow and red head and black feathers.",
"a male house finch perches in a tree at the san diego zoo.",
"biological species on a branch.",
"a bird sitting on a branch with a bird perched on it.",
"a bird perched on a branch in a tree.",
"a male house finch perches on a branch in the middle of a field.",
"a small bird perched on a branch.",
"a small bird perched on a branch of a tree.",
"a small bird perched on a bird feeder.",
"a bird sitting on top of a plant.",
"a yellow and black bird with a red head and black head and yellow breast.",
"a bird flying in the air with a branch of flowers.",
"a bird sitting on a branch in the water.",
"a bird is sitting in a tree branch.",
"a male house finch perches on a barbed wire fence in the garden.",
"a bird perched on a flower.",
"a male house finch sitting on a bird feeder.",
"a small bird perched on a branch with a bird on it ' s beak.",
White_Crowned_Sparrow_0019_127652"a bird perched on a branch with a blurry background.",
White_Crowned_Sparrow_0118_127919"a small bird standing on the ground next to a leaf.",
White_Crowned_Sparrow_0107_128662"a bird perched on a fence post.",
White_Crowned_Sparrow_0068_126156"a bird sitting in a tree looking at the camera.",
White_Crowned_Sparrow_0031_126457"a small bird standing on the ground.",
White_Crowned_Sparrow_0064_126467"a small bird sitting in a blue flower pot.",
White_Crowned_Sparrow_0093_126531"a bird standing on a rock in the middle of a field.",
White_Crowned_Sparrow_0114_127027"a bird perched on a branch in a tree.",
White_Crowned_Sparrow_0076_127604"a female house sparrow in the rain.",
White_Crowned_Sparrow_0101_127058"biological species is a common bird.",
White_Crowned_Sparrow_0085_127194"a bird is perched on a branch with flowers.",
White_Crowned_Sparrow_0044_127386"a bird perched on a branch.",
White_Crowned_Sparrow_0100_126267"a bird perched on a branch.",
White_Crowned_Sparrow_0037_126969"a bird sitting in a tree.",
White_Crowned_Sparrow_0140_125967"a bird perched on a branch.",
White_Crowned_Sparrow_0124_128082"a bird perched on a branch of a tree.",
White_Crowned_Sparrow_0002_127774"a bird perched on top of a tree branch.",
White_Crowned_Sparrow_0099_127213"a bird sitting on a fence in the woods.",
White_Crowned_Sparrow_0127_126923"a bird eating a piece of food on the ground.",
White_Crowned_Sparrow_0040_127313"a small bird perched on a branch in a tree.",
White_Crowned_Sparrow_0095_127118"a small bird standing on a tree branch.",
White_Crowned_Sparrow_0057_127927"a small bird standing on a post in the dirt.",
White_Crowned_Sparrow_0061_126315"a small bird perched on a twig.",
White_Crowned_Sparrow_0071_127922"a bird perched on a branch with a green background.",
White_Crowned_Sparrow_0054_126068"a bird perched on a rock looking at the camera.",
White_Crowned_Sparrow_0141_127766"a small bird standing on a wooden ledge.",
White_Crowned_Sparrow_0042_128395"a bird standing on the ground in the middle of a forest.",
White_Crowned_Sparrow_0129_127860"a small bird standing on the ground with a yellow beak.",
White_Crowned_Sparrow_0010_127651"a bird sitting on a wooden fence post.",
White_Crowned_Sparrow_0109_128529"a bird on a fence.",
Gray_Kingbird_0030_70110"a bird perched on a branch with leaves.",
Gray_Kingbird_0077_70191"a bird sitting on a branch.",
Gray_Kingbird_0055_70290"a bird sitting on a fence post.",
Gray_Kingbird_0060_795021"a bird perched on a branch with a sky background.",
Gray_Kingbird_0032_70111"a bird perched on a wire.",
Gray_Kingbird_0045_70256"a bird perched on a branch.",
Gray_Kingbird_0009_795023"a bird sitting on a branch in a tree.",
Gray_Kingbird_0016_70288"a bird sitting on top of a barbed wire fence.",
Gray_Kingbird_0068_70292"a bird perched on a tree branch.",
Gray_Kingbird_0081_70276"a bird sitting on top of a barbed wire fence.",
Gray_Kingbird_0043_795032"a bird sitting on a branch.",
Gray_Kingbird_0023_795035"a bird sitting on a tree branch in the park.",
Gray_Kingbird_0083_70162"a bird sitting on a wire with a gray background.",
Gray_Kingbird_0018_70241"a bird perched on a tree branch with leaves.",
Gray_Kingbird_0028_70303"a small bird sitting on a pole.",
Gray_Kingbird_0035_795027"a bird perched on a branch in a tree.",
Gray_Kingbird_0056_70156"a bird sitting on a wire with a green background.",
Gray_Kingbird_0051_70139"a bird sitting on a wire with a blue sky background.",
Gray_Kingbird_0022_70155"a bird perched on a branch with a blurry background.",
Gray_Kingbird_0003_70305"a bird sitting on a wire with a cloudy sky in the background.",
Gray_Kingbird_0049_795022"a bird sitting on a branch in the water.",
Gray_Kingbird_0084_70171"a bird sitting on a branch.",
Gray_Kingbird_0054_70264"a bird perched on a branch with a tree in the background.",
Gray_Kingbird_0019_795013"a bird sitting on a branch with a blurry background.",
Gray_Kingbird_0038_70118"a bird sitting on a branch in a tree.",
Gray_Kingbird_0036_70184"a bird perched on a branch with a blue sky in the background.",
Gray_Kingbird_0053_70166"a bird sitting on top of a wire.",
Gray_Kingbird_0004_70293"a bird sitting on a wire.",
Gray_Kingbird_0069_70082"a bird sitting on a branch in the sun.",
Gray_Kingbird_0063_70287"a bird perched on a post.",
Black_Throated_Blue_Warbler_0099_161524"a bird perched on a tree branch.",
Black_Throated_Blue_Warbler_0100_161622"a bird perched on a branch in a tree.",
Black_Throated_Blue_Warbler_0076_161162"a bird is sitting on a branch in a tree.",
Black_Throated_Blue_Warbler_0004_161404"a bird perched on a branch in a tree.",
Black_Throated_Blue_Warbler_0090_161507"a bird sitting on a tree branch in the woods.",
Black_Throated_Blue_Warbler_0024_161619"a painting of a bird sitting on a branch.",
Black_Throated_Blue_Warbler_0113_161407"a bird perched on a branch of a tree.",
Black_Throated_Blue_Warbler_0104_161686"a bird sitting on a branch in a tree.",
Black_Throated_Blue_Warbler_0001_161189"a bird perched on a branch in a tree.",
Black_Throated_Blue_Warbler_0129_161399"a small bird is perched on a hand.",
Black_Throated_Blue_Warbler_0083_161462"a small bird sitting on a branch in a tree.",
Black_Throated_Blue_Warbler_0133_161539"a bird perched on a branch of a tree.",
Black_Throated_Blue_Warbler_0017_161220"a bird perched on a tree branch.",
Black_Throated_Blue_Warbler_0127_161176"a black and white bird perched on a tree branch.",
Black_Throated_Blue_Warbler_0064_161656"a black and white bird sitting on a branch.",
Black_Throated_Blue_Warbler_0022_161520"a black and white bird perched on a branch.",
Black_Throated_Blue_Warbler_0109_161635"a black bird with a white patch on its head.",
Black_Throated_Blue_Warbler_0002_161533"a bird perched on a branch of a tree.",
Black_Throated_Blue_Warbler_0047_161511"a bird perched on a branch with a blurry background.",
Black_Throated_Blue_Warbler_0101_161510"a bird sitting on a rock in a garden.",
Black_Throated_Blue_Warbler_0010_161169"a bird perched on a tree branch.",
Black_Throated_Blue_Warbler_0054_161158"a bird sitting on a tree branch with leaves.",
Black_Throated_Blue_Warbler_0136_161400"a blue and white bird sitting on a branch.",
Black_Throated_Blue_Warbler_0130_161682"a bird standing on a branch in the sun.",
Black_Throated_Blue_Warbler_0043_161438"a small bird perched on a branch in a tree.",
Black_Throated_Blue_Warbler_0016_161216"a bird perched on a tree branch.",
Black_Throated_Blue_Warbler_0110_161726"a bird sitting on a branch in a tree.",
Black_Throated_Blue_Warbler_0126_161724"a small bird sitting on a tree branch.",
Black_Throated_Blue_Warbler_0036_161517"a bird perched on a branch in a tree.",
Black_Throated_Blue_Warbler_0060_161644"a bird perched on a branch in a tree.",
Forsters_Tern_0116_151688"a bird standing on the sand with a bird in the background.",
Forsters_Tern_0064_152047"a bird standing on a mud patch in the water.",
Forsters_Tern_0027_151456"a bird with a long beak standing on a beach.",
Forsters_Tern_0065_152206"a bird standing on top of a buoy in the water.",
Forsters_Tern_0125_151399"a bird standing on a log in the water.",
Forsters_Tern_0066_151478"a bird on a post.",
Forsters_Tern_0035_151757"a bird with an orange beak standing on a post.",
Forsters_Tern_0121_151385"biological species is a bird of the species.",
Forsters_Tern_0042_151644"a bird flying over the ocean in san diego, ca.",
Forsters_Tern_0032_151384"a bird standing on a rock in the water.",
Forsters_Tern_0034_152667"a white bird with a black beak flying in the air.",
Forsters_Tern_0016_152463"a bird with a glove on its hand.",
Forsters_Tern_0004_152358"a bird standing in a body of water.",
Forsters_Tern_0114_152768"a bird standing on the sand on a beach.",
Forsters_Tern_0080_152521"a bird is standing on a pole in the desert.",
Forsters_Tern_0062_151780"a bird with its wings spread out on a wooden ledge.",
Forsters_Tern_0088_151893"biological species in flight against a blue sky.",
Forsters_Tern_0086_152738"a bird standing on the sand near the water.",
Forsters_Tern_0119_152709"biological species in flight with a white background.",
Forsters_Tern_0100_151774"biological species on the beach.",
Forsters_Tern_0075_152258"a bird with its wings spread out in the water.",
Forsters_Tern_0098_151258"a bird is flying over the water with a fish in it ' s mouth.",
Forsters_Tern_0097_151731"a bird flying in the air with its wings spread.",
Forsters_Tern_0069_151229"a bird flying in the sky.",
Forsters_Tern_0021_144734"a bird is wading in the water.",
Forsters_Tern_0123_151789"a bird with a long beak is flying over a body of water.",
Forsters_Tern_0003_151547"a bird standing on the sand near the water.",
Forsters_Tern_0089_152372"a bird standing on the ground with a red plant in the background.",
Forsters_Tern_0017_152696"a bird flying over the beach in the san diego bay area.",
Forsters_Tern_0059_151269"a bird perched on top of a metal pole.",
Artic_Tern_0116_143613"a bird with a black head and red beak standing on a rock.",
Artic_Tern_0112_141893"a black - billed gull flying in front of a green tree.",
Artic_Tern_0026_141839"a bird with a long beak standing on a fence.",
Artic_Tern_0115_142570"a bird sitting on a piece of wood in a field.",
Artic_Tern_0124_142121"a bird flying over a body of water.",
Artic_Tern_0129_141395"a bird with a fish in its beak.",
Artic_Tern_0015_141829"a white bird with a red beak flying in the air.",
Artic_Tern_0035_143366"a bird with a red beak standing on a rock.",
Artic_Tern_0089_141652"a white - winged blackbird landing in a field of grass.",
Artic_Tern_0052_143244"biological species is a species of birds.",
Artic_Tern_0105_141098"a white bird flying in the sky with a cloudy sky background.",
Artic_Tern_0127_142440"a bird standing on a rock covered beach.",
Artic_Tern_0011_143355"biological species in flight against a blue sky.",
Artic_Tern_0102_141453"biological species in flight with a fish in its beak.",
Artic_Tern_0063_142495"a bird is perched on a post in a field.",
Artic_Tern_0019_141922"biological species in flight with a fish in its beak.",
Artic_Tern_0090_143583"a bird with a beak that is sitting on a branch.",
Artic_Tern_0065_141472"biological species in flight against a blue sky.",
Artic_Tern_0032_141313"a bird with a red beak standing on a fence.",
Artic_Tern_0029_142220"a bird with a black head and red feet.",
Artic_Tern_0027_141617"a bird standing in the grass with a red beak.",
Artic_Tern_0142_142078"a white bird with a red beak stands on a post.",
Artic_Tern_0101_141075"a black and white bird with a red beak.",
Artic_Tern_0122_142448"a white bird flying in the sky with its wings spread.",
Artic_Tern_0117_143394"a bird standing on the sand on a beach.",
Artic_Tern_0023_140898"biological species in flight against a blue sky.",
Artic_Tern_0111_143101"a seagull flying in the sky with a fish in its beak.",
Artic_Tern_0034_142022"a bird with a red beak standing on a wooden post.",
Artic_Tern_0048_142372"a bird flying in the sky with a red beak.",
Horned_Puffin_0019_101063"a penguin standing on a rock in a field.",
Horned_Puffin_0029_100888"a duck swimming in the water.",
Horned_Puffin_0010_100771"a bird with a red beak.",
Horned_Puffin_0056_101030"a bird with a yellow beak standing on a rock.",
Horned_Puffin_0081_101054"a close up of a bird with a beak.",
Horned_Puffin_0050_100645"a bird flying over the water with its wings spread.",
Horned_Puffin_0059_100925"a puffin swimming in the water.",
Horned_Puffin_0067_100737"a bird standing on a rock in the middle of a forest.",
Horned_Puffin_0025_100942"a bird with a beak and a beak.",
Horned_Puffin_0073_100830"a bird floating on top of a body of water.",
Horned_Puffin_0055_100882"a bird with a yellow beak standing on a rock.",
Horned_Puffin_0084_100637"a bird with a beak and a beak.",
Horned_Puffin_0035_100690"a puffin with a beak full of feathers.",
Horned_Puffin_0027_100906"a bird with a large beak and yellow beak.",
Horned_Puffin_0048_100916"a duck swimming in the water at the san diego zoo.",
Horned_Puffin_0071_100651"a bird sitting on a rock with a beak.",
Horned_Puffin_0012_100763"a bird with wings spread out on a rock.",
Horned_Puffin_0007_100699"a puffin with a yellow beak floating in the water.",
Horned_Puffin_0062_100693"a bird with a yellow beak and a black beak.",
Horned_Puffin_0082_100876"a bird sitting on a rock with a blue sky in the background.",
Horned_Puffin_0074_100886"a bird with a beak sitting on a rock.",
Horned_Puffin_0079_100847"a bird standing on a rock with moss on it ' s side.",
Horned_Puffin_0036_100974"a bird with a fish in its mouth.",
Horned_Puffin_0052_100977"a puffin taking a bath in the water.",
Horned_Puffin_0006_100989"a bird with a yellow beak and a white head.",
Horned_Puffin_0038_100635"a bird with an open beak standing on a rock.",
Horned_Puffin_0069_101018"a bird with a long beak and a large beak.",
Horned_Puffin_0083_100649"a bird sitting on a rock with a black background.",
Horned_Puffin_0047_100967"a male puffin with a white head and a black head.",
Horned_Puffin_0060_100726"a bird with a yellow beak standing on a branch.",
Cape_Glossy_Starling_0013_129244"a blue bird sitting on a branch in a tree.",
Cape_Glossy_Starling_0012_129225"a blue bird sitting on a branch in a tree.",
Cape_Glossy_Starling_0006_129295"a bird with a yellow eye sitting on a wooden table.",
Cape_Glossy_Starling_0072_129386"a blue bird standing on a post.",
Cape_Glossy_Starling_0018_129356"a blue bird sitting on a metal fence.",
Cape_Glossy_Starling_0099_129412"a bird sitting on a branch of a tree.",
Cape_Glossy_Starling_0025_129341"a blue bird sitting on a black object.",
Cape_Glossy_Starling_0022_129414"a bird standing on a rock in the desert.",
Cape_Glossy_Starling_0019_129407"a blue bird perched on a plant with yellow eyes.",
Cape_Glossy_Starling_0034_129455"a colorful bird standing on a ledge.",
Cape_Glossy_Starling_0033_129435"a bird perched on a branch.",
Cape_Glossy_Starling_0065_129299"a bird perched on a branch in a tree.",
Cape_Glossy_Starling_0015_129266"a bird is standing on a wooden table.",
Cape_Glossy_Starling_0046_129434"a bird perched on a branch.",
Cape_Glossy_Starling_0097_129303"a bird with orange eyes sitting on a ledge.",
Cape_Glossy_Starling_0002_129310"a blue bird standing on the ground in a field.",
Cape_Glossy_Starling_0060_129222"a bird perched on a branch.",
Cape_Glossy_Starling_0050_129274"a blue bird walking through the grass.",
Cape_Glossy_Starling_0027_129282"a bird that is standing on a dirt ground.",
Cape_Glossy_Starling_0016_129464"a bird perched on a chair in the sun.",
Cape_Glossy_Starling_0054_129440"biological species is a species of bird.",
Cape_Glossy_Starling_0059_129357"a small bird with a yellow eye standing on the ground.",
Cape_Glossy_Starling_0070_129322"a male blue bird in a tree.",
Cape_Glossy_Starling_0005_129262"a blue bird sitting on top of a wooden table.",
Cape_Glossy_Starling_0020_129328"a bird standing in the sand looking at the camera.",
Cape_Glossy_Starling_0075_129431"a bird perched on a wooden post.",
Cape_Glossy_Starling_0098_129365"a bird with a yellow eye standing on a branch.",
Cape_Glossy_Starling_0079_129399"a bird standing on the ground in the sun.",
Cape_Glossy_Starling_0067_129380"a bird standing on a branch.",
Cape_Glossy_Starling_0026_129288"a colorful bird standing on the ground.",
Olive_Sided_Flycatcher_0031_30502"a small bird perched on a branch with a twig in its mouth.",
Olive_Sided_Flycatcher_0056_30570"a person holding a bird in their hand.",
Olive_Sided_Flycatcher_0008_30686"a bird in a tree.",
Olive_Sided_Flycatcher_0078_30752"a bird perched on a tree branch.",
Olive_Sided_Flycatcher_0033_30532"a person holding a bird in their hand.",
Olive_Sided_Flycatcher_0055_796879"a male black - crowned kingfisher perched on a branch in a tree in the san diego zoo.",
Olive_Sided_Flycatcher_0001_30669"a bird sitting on a branch in a tree.",
Olive_Sided_Flycatcher_0080_30515"a bird perched on a branch.",
Olive_Sided_Flycatcher_0075_30712"a bird sitting on a branch with a blue sky in the background.",
Olive_Sided_Flycatcher_0002_30776"a bird sitting on a wooden fence post.",
Olive_Sided_Flycatcher_0021_796880"a bird perched on a pole.",
Olive_Sided_Flycatcher_0020_796881"a bird in a tree.",
Olive_Sided_Flycatcher_0041_30470"a bird sitting on a branch with a blue sky in the background.",
Olive_Sided_Flycatcher_0046_30529"a bird perched on a tree branch.",
Olive_Sided_Flycatcher_0079_30662"a small bird perched on a branch.",
Olive_Sided_Flycatcher_0017_30704"a bird sitting on a wire with a blue sky in the background.",
Olive_Sided_Flycatcher_0035_30799"a bird sitting on a power line.",
Olive_Sided_Flycatcher_0082_796893"a bird sitting on a branch.",
Olive_Sided_Flycatcher_0059_30536"a bird perched on a branch of a tree.",
Olive_Sided_Flycatcher_0067_30749"a bird perched on a thin branch.",
Olive_Sided_Flycatcher_0058_796883"a bird perched on a branch.",
Olive_Sided_Flycatcher_0086_30553"a bird sitting on a branch with a piece of food in its mouth.",
Olive_Sided_Flycatcher_0081_796895"biological species perched on a twig.",
Olive_Sided_Flycatcher_0034_30672"a bird sitting on a branch of a tree.",
Olive_Sided_Flycatcher_0074_30816"a bird standing on a beach next to seaweed.",
Olive_Sided_Flycatcher_0076_30555"a bird perched on a branch in the snow.",
Olive_Sided_Flycatcher_0018_796882"biological species perched on a branch.",
Olive_Sided_Flycatcher_0050_796878"a bird sitting on a tree branch.",
Olive_Sided_Flycatcher_0057_796898"a female black - backed woodpecker sits on a branch.",
Olive_Sided_Flycatcher_0038_796884"a bird perched on a branch.",
Le_Conte_Sparrow_0043_795213"a bird perched on a branch.",
Le_Conte_Sparrow_0092_795221"a bird sitting on a branch in a tree.",
Le_Conte_Sparrow_0071_795185"a bird is sitting on a branch in a tree.",
Le_Conte_Sparrow_0061_795194"a small bird perched on a tree branch.",
Le_Conte_Sparrow_0039_117054"a bird perched on a tree branch.",
Le_Conte_Sparrow_0050_795143"a bird perched on a branch of a tree.",
Le_Conte_Sparrow_0007_795148"biological species is a native.",
Le_Conte_Sparrow_0083_795163"biological species is a species of birds.",
Le_Conte_Sparrow_0032_795186"a bird sitting on a branch in a tree.",
Le_Conte_Sparrow_0023_795156"a bird perched on a thin branch.",
Le_Conte_Sparrow_0005_795137"a bird perched on a tree branch in a tree.",
Le_Conte_Sparrow_0047_795192"a bird standing on a branch in a field.",
Le_Conte_Sparrow_0098_795231"a bird perched on a branch in a tree.",
Le_Conte_Sparrow_0087_795198"a female house sparrow in the garden.",
Le_Conte_Sparrow_0046_795227"a bird perched on a branch of a tree.",
Le_Conte_Sparrow_0045_795162"a small bird perched on a rock.",
Le_Conte_Sparrow_0084_795189"a bird sitting on a branch in the woods.",
Le_Conte_Sparrow_0049_795220"a bird in a tree.",
Le_Conte_Sparrow_0056_795178"a bird in the grass.",
Le_Conte_Sparrow_0041_795218"a bird sitting on a branch in a field.",
Le_Conte_Sparrow_0006_795146"a bird sitting on a branch in a tree.",
Le_Conte_Sparrow_0088_117040"a bird in a tree.",
Le_Conte_Sparrow_0099_795182"a bird is sitting in a bush in the middle of the day.",
Le_Conte_Sparrow_0068_795180"a small bird perched on a branch.",
Le_Conte_Sparrow_0067_117146"a bird perched on a branch of a tree.",
Le_Conte_Sparrow_0075_795234"a bird sitting in a nest in the middle of a field.",
Le_Conte_Sparrow_0011_117038"a bird sitting on top of a tall grass.",
Le_Conte_Sparrow_0081_795215"a bird is sitting on a branch.",
Le_Conte_Sparrow_0034_795150"a small bird sitting on a branch in a field.",
Le_Conte_Sparrow_0012_795211"a bird is sitting on a branch in the grass.",
Purple_Finch_0117_27427"a red bird sitting on a fence post.",
Purple_Finch_0108_28143"a red bird perched on a branch in a tree.",
Purple_Finch_0033_27926"a red bird perched on a branch in a tree.",
Purple_Finch_0043_28117"biological species perched on a branch.",
Purple_Finch_0011_27633"a bird standing on the ground in the middle of the road.",
Purple_Finch_0035_27972"a small bird sitting on a bird feeder.",
Purple_Finch_0030_27255"a red bird perched on a metal pole.",
Purple_Finch_0049_27507"a bird sitting on a bird feeder.",
Purple_Finch_0133_27928"a small bird perched on a tree branch.",
Purple_Finch_0004_27565"biological species in the snow.",
Purple_Finch_0103_27461"a bird with a pink head and beak on a branch.",
Purple_Finch_0025_28174"a small bird perched on a branch in a tree.",
Purple_Finch_0092_27264"a male house finch perches on a branch in a tree.",
Purple_Finch_0094_27323"a red and black bird on a bird feeder.",
Purple_Finch_0005_27512"a bird sitting on a wire.",
Purple_Finch_0036_27641"a small bird on a wet wooden deck.",
Purple_Finch_0002_27266"a male house finch perches on a metal ring in the garden.",
Purple_Finch_0088_28076"a bird perched on a branch in the forest.",
Purple_Finch_0001_27571"a red bird sitting on a perch.",
Purple_Finch_0081_27913"a small bird sitting on a metal bar.",
Purple_Finch_0046_27295"a bird perched on a branch.",
Purple_Finch_0130_27555"biological species on a branch.",
Purple_Finch_0115_28190"a female house finch feeding on a seed in my garden.",
Purple_Finch_0114_27837"a bird perched on a branch in a tree.",
Purple_Finch_0053_27543"a red bird standing on top of a bird feeder.",
Purple_Finch_0104_28088"a bird sitting on a lamp post.",
Purple_Finch_0008_27455"a red bird sitting on a metal railing.",
Purple_Finch_0098_27280"a red bird sitting on a bird feeder in the garden.",
Purple_Finch_0006_27950"a red - winged blackbird perches on a metal fence in the backyard of my house in san diego, california.",
Purple_Finch_0021_28235"a male house finch perches on a bird feeder in the garden."]

detailed_list = [label.split()]